### ISSUE TITLE
0.05 является строгим ограничением, поэтому мы не можем вводить данное значение

### ISSUE THREAD

**Issue by 3rOFd** [DmitrTRC/LevelUP_C_Part_1#2]
https://github.com/DmitrTRC/LevelUP_C_Part_1/blob/d6098a0e8a68e86a2317bdcb49fb7db09ef7bf7b/HomeWork_3_5/tests/test_task5.cpp#L15

**Comment by DmitrTRC** [comment]
Исправлена проверка условий в main()
Что касается теста - тут мы вольны тестировать любые требуемые для оценки работы кейсы.
