### ISSUE TITLE
Замечания HomeWork_3_1

### ISSUE THREAD

**Issue by imirrori** [DmitrTRC/LevelUP_C_Part_1#5]
Подключены файлы в неправльном порядке
https://github.com/DmitrTRC/LevelUP_C_Part_1/blob/0290a07877c37110c0b6ee52e74dc97c8210121b/HomeWork_3_1/src/main.cpp#L5

Неиспользуемые параметры
https://github.com/DmitrTRC/LevelUP_C_Part_1/blob/0290a07877c37110c0b6ee52e74dc97c8210121b/HomeWork_3_1/src/main.cpp#L10

Лишняя пустая строка
https://github.com/DmitrTRC/LevelUP_C_Part_1/blob/0290a07877c37110c0b6ee52e74dc97c8210121b/HomeWork_3_1/src/main.cpp#L11

Использован стандарт С++20
https://github.com/DmitrTRC/LevelUP_C_Part_1/blob/0290a07877c37110c0b6ee52e74dc97c8210121b/HomeWork_3_1/src/Task1.cpp#L4

**Comment by DmitrTRC** [comment]
Fixed.
