### ISSUE TITLE
Question about two strings after while-loop

### ISSUE THREAD

**Issue by posdima** [DmitrTRC/LevelUP_C_Part_1#7]
Don't understand why you repeat this two strings again after while-loop

https://github.com/DmitrTRC/LevelUP_C_Part_1/blob/9189058d9aaf75e7b9f11adafd0f23f076b573ce/HomeWork_Week_3/HW_5/src/df_seq.cpp#L55

https://github.com/DmitrTRC/LevelUP_C_Part_1/blob/9189058d9aaf75e7b9f11adafd0f23f076b573ce/HomeWork_Week_3/HW_5/src/df_seq.cpp#L56

**Comment by DmitrTRC** [comment]
Братан ! - Просто респект!!! Вместо Cmd+x , Cmd+v нажал Cmd+c , Cmd+v
Но на суть то сильно не влияет - приращение уже меньше Epsilon.
Anyway : Отлично что выловил.

**Comment by DmitrTRC** [comment]
Беда то в другом - у нас ответ близок , но разный...
Буду тестировать...

**Comment by posdima** [comment]
Вчера пока мучил калькулятор и отладчик, решил твой код глянуть. Там и заметил. 
Сам не понимаю - почему у нас результаты расходятся
